PATH_TO_DATA     = "lemon-dataset/"
PATH_TO_IMAGES   = "lemon-dataset/images/"
PATH_TO_ANNOT    = "lemon-dataset/annotations/instances_default.json"
PATH_TO_NPY      = "store/stored-data.npy"
PATH_TO_GEN_IMG0 = "store/gen-images-0.npy"
PATH_TO_GEN_IMG1 = "store/gen-images-1.npy"
PATH_TO_MODEL    = "store/saved-model.h5"
PATH_TO_CKP      = "store/checkpoint"
PATH_TO_GEN      = "store/saved-gen-model.h5"
PATH_TO_DICT     = "store/dict.pickle"
IMG_SIZE         = 256
BATCH_SIZE       = 64
BUFFER_SIZE      = 1024
LATENT_DIM       = 128
NUM_CLASSES      = 2
NUM_CHANNELS     = 3
GEN_IN_CHANNELS  = LATENT_DIM + NUM_CLASSES
DIS_IN_CHANNELS  = NUM_CHANNELS + NUM_CLASSES
